package io.github.pigerzhu.onelab.system;

public final class ThermalHardBypassScript {
    private ThermalHardBypassScript() {
    }

    public static String build() {
        return String.join("\n",
                "STATE_DIR=/data/local/tmp/onelab-thermal-hard-bypass",
                "PID_FILE=$STATE_DIR/pid",
                "ZONE_FILE=$STATE_DIR/zones",
                "CDEV_FILE=$STATE_DIR/cdevs",
                "BATTERY_LIMIT=450",
                "JUNCTION_LIMIT=100000",
                "SETTING=onelab_thermal_hard_bypass",
                "STATUS=onelab_thermal_hard_bypass_status",
                "restore_reason=user_disabled",
                "",
                "if [ -r \"$PID_FILE\" ]; then",
                "  read -r old_pid < \"$PID_FILE\"",
                "  kill -0 \"$old_pid\" 2>/dev/null && exit 0",
                "fi",
                "rm -rf \"$STATE_DIR\"",
                "mkdir -p \"$STATE_DIR\" || exit 1",
                "echo $$ > \"$PID_FILE\"",
                "",
                "thermal_engine_was=$(getprop init.svc.thermal-engine)",
                "samsung_hal_pid=$(pidof vendor.samsung.hardware.thermal-service)",
                "",
                "restore() {",
                "  trap - EXIT TERM INT HUP",
                "  if [ -r \"$ZONE_FILE\" ]; then",
                "    while IFS='|' read -r z mode; do",
                "      [ -n \"$z\" ] && [ -w \"$z/mode\" ] && echo \"$mode\" > \"$z/mode\"",
                "    done < \"$ZONE_FILE\"",
                "  fi",
                "  [ \"$thermal_engine_was\" = running ] && start thermal-engine >/dev/null 2>&1",
                "  [ -n \"$samsung_hal_pid\" ] && start vendor.samsung.hardware.thermal-default >/dev/null 2>&1",
                "  settings put global \"$STATUS\" \"restored:$restore_reason\"",
                "  rm -rf \"$STATE_DIR\"",
                "}",
                "trap restore EXIT TERM INT HUP",
                "",
                ": > \"$CDEV_FILE\"",
                "for c in /sys/class/thermal/cooling_device*; do",
                "  [ -r \"$c/type\" ] || continue",
                "  IFS= read -r type < \"$c/type\"",
                "  case \"$type\" in",
                "    cpufreq-cpu*|cpu-cluster*|gpu|display-fps) echo \"$c\" >> \"$CDEV_FILE\" ;;",
                "  esac",
                "done",
                "",
                ": > \"$ZONE_FILE\"",
                "for z in /sys/class/thermal/thermal_zone*; do",
                "  [ -w \"$z/mode\" ] || continue",
                "  matched=0",
                "  for link in \"$z\"/cdev*; do",
                "    [ -L \"$link\" ] || continue",
                "    target=$(readlink \"$link\")",
                "    target=${target##*/}",
                "    while IFS= read -r c; do",
                "      [ \"${c##*/}\" = \"$target\" ] && matched=1",
                "    done < \"$CDEV_FILE\"",
                "  done",
                "  if [ \"$matched\" = 1 ]; then",
                "    IFS= read -r mode < \"$z/mode\"",
                "    echo \"$z|$mode\" >> \"$ZONE_FILE\"",
                "    echo disabled > \"$z/mode\"",
                "  fi",
                "done",
                "",
                "stop thermal-engine >/dev/null 2>&1",
                "stop vendor.samsung.hardware.thermal-default >/dev/null 2>&1",
                "sleep 1",
                "while IFS= read -r c; do [ -w \"$c/cur_state\" ] && echo 0 > \"$c/cur_state\"; done < \"$CDEV_FILE\"",
                "settings put global \"$STATUS\" active",
                "",
                "while [ \"$(settings get global \"$SETTING\")\" = 1 ]; do",
                "  battery=0",
                "  [ -r /sys/class/power_supply/battery/temp ] && IFS= read -r battery < /sys/class/power_supply/battery/temp",
                "  junction=0",
                "  for z in /sys/class/thermal/thermal_zone*; do",
                "    [ -r \"$z/type\" ] && [ -r \"$z/temp\" ] || continue",
                "    IFS= read -r type < \"$z/type\"",
                "    case \"$type\" in cpu*|cpuss*|gpu*|gpuss*|ddr) IFS= read -r temp < \"$z/temp\"; [ \"$temp\" -gt \"$junction\" ] 2>/dev/null && junction=$temp ;; esac",
                "  done",
                "  if [ \"$battery\" -ge \"$BATTERY_LIMIT\" ] 2>/dev/null || [ \"$junction\" -ge \"$JUNCTION_LIMIT\" ] 2>/dev/null; then",
                "    restore_reason=emergency:battery=$battery,junction=$junction",
                "    settings put global \"$STATUS\" \"$restore_reason\"",
                "    settings put global onelab_thermal_hard_bypass 0",
                "    break",
                "  fi",
                "  sleep 1",
                "done",
                "") + "\n";
    }
}
